### ISSUE TITLE
Support Raspbian for Raspberry Pi

### ISSUE THREAD

**Issue by keryell** [HanXHX/ansible-debian-bootstrap#20]
I worked a little bit with https://github.com/rhietala/raspberry-ansible
where there is a copy of https://github.com/HanXHX/ansible-debian-bootstrap

I have played with an updated version for Stretch merged from here into https://github.com/keryell/raspberry-ansible/tree/stretch as tracked by https://github.com/rhietala/raspberry-ansible/pull/3

As you said in https://github.com/rhietala/raspberry-ansible/issues/2 it would be nice that https://github.com/HanXHX/ansible-debian-bootstrap were just usable for Raspberry Pi.
From what I understand the only main issue is that for Debian `vars/debian.yml`has hardcoded `debian` name in it while it is `raspbian` for Raspbian.
So instead of having a new `vars/raspbian.yml` with the name `raspbian` in it, it could be a common file using a new variable to specify the detail of the distribution names in the URL.
Probably the Devuan option could be factorized out this way too.

**Comment by HanXHX** [comment]
I need to find a simple way to emulate rpi with raspbian (i use Vagrant + Virtualbox/Docker)...

If you have any tip, i'll can update my code :)

**Comment by keryell** [comment]
Of course, if you want to do some CI it is more difficult...
At least you can check that the Raspbian add-on does not break Debian/Devuan on x86. :-)

Otherwise it might be possible to test on a real Raspberry Pi running... Docker for example.
Or emulation with QEMU:
https://stackoverflow.com/questions/38837606/emulate-raspberry-pi-raspbian-with-qemu
https://azeria-labs.com/emulate-raspberry-pi-with-qemu/
https://blog.agchapman.com/using-qemu-to-emulate-a-raspberry-pi/
But it is not using exactly the same kernel since some parts of the hardware are not available.

**Comment by HanXHX** [comment]
Kernel is not a problem (my role works well on Docker). I'll have a look in few days. But you can send me a PR ;)

**Comment by ValentinFunk** [comment]
@HanXHX for CI maybe use a scaleway ARM server

**Comment by smougenot** [comment]
@HanXHX looks done
Maybe it is time to close this issue
