### ISSUE TITLE
Better instructions for nubes

### ISSUE THREAD

**Issue by clarkezone** [HanXHX/ansible-debian-bootstrap#33]
This looks interesting but as someone who has minimal ansible knowledge I have no clue how to use it to set up a bunch of RaPi's to have hostnames, etc.  Please consider adding more extensive examples to help ease into it from lower knowledge starting point.  THx!

**Comment by HanXHX** [comment]
Hi @clarkezone,

Sorry for the late. I didn't see your issue.

I don't provide any support for rapsi (i never use it with this role), marked as 'experimental'. The raspi code comes from an old PR... And I can't test it with a VM (no official raspbian vagrant box).

Best,
